dist: xenial
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    -   secure: "VBJ/jb21wQc62GHgt/sK09glULV8Vwb2ACO5+oyoAyOc0CJ46UaE9Zeg8cw3mUXJhhxQmmbFXNG3hcvhP1xsdcXYFWXbuSFA63YKkqERR4ri8bK5AkoI0OaEqhf7ENa4MLdBRclZOmh70iyesv9e7
+cGSCZSWrQX5bnQAkTu4rmMdnhz5ik6w8D8jDIn8KO2Qk0NpzYd5LCEJPyCj1EwsQ/IlHbV8EjyO/9Fop99bqdd0nMs2/JgT2a3geBUb0N5JbmnXsy2GGCLVvmPdAzxPApJRjBbayePY+41mV51zRbNnP78K+jqV
NB7MAp+27XJOtfgArkYuepDxLSTB97IYgT0t6Ejo2UPKE1uUrotW3IGOLwtH9cGlGCOzosDRStLI5QrJiuLXHT6BE3VPossA+HjxL35SC0JKpw72vd63jK229751z69XZbF2ZgvJrB4FdSX8LKzlPmCQzeHdY3Z3
Mxv67fU8FtevkfLrTWgHxB907LoFm8pi43qxmu66sPzl70i6CfRaX4Hoj/z6CFA5znM/xVnphDfjNvA0D3rcFb/tqjoQRYWGrukucywoFULdwLlX5kAz6jXAjupP371M3OkSXwtZvLLGuEALftIBxCj4UjWnBlS3
ekpHqOoZgDtccr7PrRyeU1NHesetVZtjFvDK62bsgQOQF/Q8e3/YP4="

install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B
    - stage: test
      jdk: openjdk12
      script:
        - mvn test -B
