//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.14 at 01:10:00 AM EET 
//


package eu.toop.simulator.schema.discovery;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.toop.simulator.schema.discovery package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ServiceMetadataList_QNAME = new QName("http://eu/toop/simulator/schema/discovery", "ServiceMetadataList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.toop.simulator.schema.discovery
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceMatadataListType }
     * 
     */
    public ServiceMatadataListType createServiceMatadataListType() {
        return new ServiceMatadataListType();
    }

    /**
     * Create an instance of {@link CountryAwareServiceMetadataType }
     * 
     */
    public CountryAwareServiceMetadataType createCountryAwareServiceMetadataType() {
        return new CountryAwareServiceMetadataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceMatadataListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eu/toop/simulator/schema/discovery", name = "ServiceMetadataList")
    public JAXBElement<ServiceMatadataListType> createServiceMetadataList(ServiceMatadataListType value) {
        return new JAXBElement<ServiceMatadataListType>(_ServiceMetadataList_QNAME, ServiceMatadataListType.class, null, value);
    }

}
