//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.14 at 01:10:00 AM EET 
//


package eu.toop.simulator.schema.discovery;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceMatadataListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceMatadataListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CountryAwareServiceMetadata" type="{http://eu/toop/simulator/schema/discovery}CountryAwareServiceMetadataType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceMatadataListType", propOrder = {
    "countryAwareServiceMetadata"
})
public class ServiceMatadataListType {

    @XmlElement(name = "CountryAwareServiceMetadata", required = true)
    protected List<CountryAwareServiceMetadataType> countryAwareServiceMetadata;

    /**
     * Gets the value of the countryAwareServiceMetadata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countryAwareServiceMetadata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountryAwareServiceMetadata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CountryAwareServiceMetadataType }
     * 
     * 
     */
    public List<CountryAwareServiceMetadataType> getCountryAwareServiceMetadata() {
        if (countryAwareServiceMetadata == null) {
            countryAwareServiceMetadata = new ArrayList<CountryAwareServiceMetadataType>();
        }
        return this.countryAwareServiceMetadata;
    }

}
