//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.14 at 01:10:00 AM EET 
//


package org.oasis_open.docs.bdxr.ns.smp._2016._05;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EndpointType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EndpointType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EndpointURI" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="RequireBusinessLevelSignature" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MinimumAuthenticationLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServiceActivationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ServiceExpirationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Certificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="ServiceDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TechnicalContactUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="TechnicalInformationUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="Extension" type="{http://docs.oasis-open.org/bdxr/ns/SMP/2016/05}ExtensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="transportProfile" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EndpointType", propOrder = {
    "endpointURI",
    "requireBusinessLevelSignature",
    "minimumAuthenticationLevel",
    "serviceActivationDate",
    "serviceExpirationDate",
    "certificate",
    "serviceDescription",
    "technicalContactUrl",
    "technicalInformationUrl",
    "extension"
})
public class EndpointType {

    @XmlElement(name = "EndpointURI", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String endpointURI;
    @XmlElement(name = "RequireBusinessLevelSignature", defaultValue = "false")
    protected Boolean requireBusinessLevelSignature;
    @XmlElement(name = "MinimumAuthenticationLevel")
    protected String minimumAuthenticationLevel;
    @XmlElement(name = "ServiceActivationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar serviceActivationDate;
    @XmlElement(name = "ServiceExpirationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar serviceExpirationDate;
    @XmlElement(name = "Certificate", required = true)
    protected byte[] certificate;
    @XmlElement(name = "ServiceDescription", required = true)
    protected String serviceDescription;
    @XmlElement(name = "TechnicalContactUrl", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String technicalContactUrl;
    @XmlElement(name = "TechnicalInformationUrl")
    @XmlSchemaType(name = "anyURI")
    protected String technicalInformationUrl;
    @XmlElement(name = "Extension")
    protected List<ExtensionType> extension;
    @XmlAttribute(name = "transportProfile", required = true)
    protected String transportProfile;

    /**
     * Gets the value of the endpointURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndpointURI() {
        return endpointURI;
    }

    /**
     * Sets the value of the endpointURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndpointURI(String value) {
        this.endpointURI = value;
    }

    /**
     * Gets the value of the requireBusinessLevelSignature property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequireBusinessLevelSignature() {
        return requireBusinessLevelSignature;
    }

    /**
     * Sets the value of the requireBusinessLevelSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequireBusinessLevelSignature(Boolean value) {
        this.requireBusinessLevelSignature = value;
    }

    /**
     * Gets the value of the minimumAuthenticationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumAuthenticationLevel() {
        return minimumAuthenticationLevel;
    }

    /**
     * Sets the value of the minimumAuthenticationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumAuthenticationLevel(String value) {
        this.minimumAuthenticationLevel = value;
    }

    /**
     * Gets the value of the serviceActivationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getServiceActivationDate() {
        return serviceActivationDate;
    }

    /**
     * Sets the value of the serviceActivationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setServiceActivationDate(XMLGregorianCalendar value) {
        this.serviceActivationDate = value;
    }

    /**
     * Gets the value of the serviceExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getServiceExpirationDate() {
        return serviceExpirationDate;
    }

    /**
     * Sets the value of the serviceExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setServiceExpirationDate(XMLGregorianCalendar value) {
        this.serviceExpirationDate = value;
    }

    /**
     * Gets the value of the certificate property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCertificate() {
        return certificate;
    }

    /**
     * Sets the value of the certificate property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCertificate(byte[] value) {
        this.certificate = value;
    }

    /**
     * Gets the value of the serviceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDescription() {
        return serviceDescription;
    }

    /**
     * Sets the value of the serviceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDescription(String value) {
        this.serviceDescription = value;
    }

    /**
     * Gets the value of the technicalContactUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnicalContactUrl() {
        return technicalContactUrl;
    }

    /**
     * Sets the value of the technicalContactUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnicalContactUrl(String value) {
        this.technicalContactUrl = value;
    }

    /**
     * Gets the value of the technicalInformationUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnicalInformationUrl() {
        return technicalInformationUrl;
    }

    /**
     * Sets the value of the technicalInformationUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnicalInformationUrl(String value) {
        this.technicalInformationUrl = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionType }
     * 
     * 
     */
    public List<ExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<ExtensionType>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the transportProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportProfile() {
        return transportProfile;
    }

    /**
     * Sets the value of the transportProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportProfile(String value) {
        this.transportProfile = value;
    }

}
