//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.14 at 01:10:00 AM EET 
//


package org.oasis_open.docs.bdxr.ns.smp._2016._05;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.oasis_open.docs.bdxr.ns.smp._2016._05 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RecipientIdentifier_QNAME = new QName("http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", "RecipientIdentifier");
    private final static QName _ProcessIdentifier_QNAME = new QName("http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", "ProcessIdentifier");
    private final static QName _SenderIdentifier_QNAME = new QName("http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", "SenderIdentifier");
    private final static QName _ServiceGroup_QNAME = new QName("http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", "ServiceGroup");
    private final static QName _DocumentIdentifier_QNAME = new QName("http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", "DocumentIdentifier");
    private final static QName _ParticipantIdentifier_QNAME = new QName("http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", "ParticipantIdentifier");
    private final static QName _ServiceMetadata_QNAME = new QName("http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", "ServiceMetadata");
    private final static QName _SignedServiceMetadata_QNAME = new QName("http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", "SignedServiceMetadata");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.oasis_open.docs.bdxr.ns.smp._2016._05
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ParticipantIdentifierType }
     * 
     */
    public ParticipantIdentifierType createParticipantIdentifierType() {
        return new ParticipantIdentifierType();
    }

    /**
     * Create an instance of {@link ServiceGroupType }
     * 
     */
    public ServiceGroupType createServiceGroupType() {
        return new ServiceGroupType();
    }

    /**
     * Create an instance of {@link SignedServiceMetadataType }
     * 
     */
    public SignedServiceMetadataType createSignedServiceMetadataType() {
        return new SignedServiceMetadataType();
    }

    /**
     * Create an instance of {@link DocumentIdentifierType }
     * 
     */
    public DocumentIdentifierType createDocumentIdentifierType() {
        return new DocumentIdentifierType();
    }

    /**
     * Create an instance of {@link ServiceMetadataType }
     * 
     */
    public ServiceMetadataType createServiceMetadataType() {
        return new ServiceMetadataType();
    }

    /**
     * Create an instance of {@link ProcessIdentifierType }
     * 
     */
    public ProcessIdentifierType createProcessIdentifierType() {
        return new ProcessIdentifierType();
    }

    /**
     * Create an instance of {@link ServiceMetadataReferenceCollectionType }
     * 
     */
    public ServiceMetadataReferenceCollectionType createServiceMetadataReferenceCollectionType() {
        return new ServiceMetadataReferenceCollectionType();
    }

    /**
     * Create an instance of {@link ServiceInformationType }
     * 
     */
    public ServiceInformationType createServiceInformationType() {
        return new ServiceInformationType();
    }

    /**
     * Create an instance of {@link RedirectType }
     * 
     */
    public RedirectType createRedirectType() {
        return new RedirectType();
    }

    /**
     * Create an instance of {@link ProcessType }
     * 
     */
    public ProcessType createProcessType() {
        return new ProcessType();
    }

    /**
     * Create an instance of {@link ServiceMetadataReferenceType }
     * 
     */
    public ServiceMetadataReferenceType createServiceMetadataReferenceType() {
        return new ServiceMetadataReferenceType();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link EndpointType }
     * 
     */
    public EndpointType createEndpointType() {
        return new EndpointType();
    }

    /**
     * Create an instance of {@link ProcessListType }
     * 
     */
    public ProcessListType createProcessListType() {
        return new ProcessListType();
    }

    /**
     * Create an instance of {@link ServiceEndpointList }
     * 
     */
    public ServiceEndpointList createServiceEndpointList() {
        return new ServiceEndpointList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParticipantIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", name = "RecipientIdentifier")
    public JAXBElement<ParticipantIdentifierType> createRecipientIdentifier(ParticipantIdentifierType value) {
        return new JAXBElement<ParticipantIdentifierType>(_RecipientIdentifier_QNAME, ParticipantIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", name = "ProcessIdentifier")
    public JAXBElement<ProcessIdentifierType> createProcessIdentifier(ProcessIdentifierType value) {
        return new JAXBElement<ProcessIdentifierType>(_ProcessIdentifier_QNAME, ProcessIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParticipantIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", name = "SenderIdentifier")
    public JAXBElement<ParticipantIdentifierType> createSenderIdentifier(ParticipantIdentifierType value) {
        return new JAXBElement<ParticipantIdentifierType>(_SenderIdentifier_QNAME, ParticipantIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceGroupType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", name = "ServiceGroup")
    public JAXBElement<ServiceGroupType> createServiceGroup(ServiceGroupType value) {
        return new JAXBElement<ServiceGroupType>(_ServiceGroup_QNAME, ServiceGroupType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", name = "DocumentIdentifier")
    public JAXBElement<DocumentIdentifierType> createDocumentIdentifier(DocumentIdentifierType value) {
        return new JAXBElement<DocumentIdentifierType>(_DocumentIdentifier_QNAME, DocumentIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParticipantIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", name = "ParticipantIdentifier")
    public JAXBElement<ParticipantIdentifierType> createParticipantIdentifier(ParticipantIdentifierType value) {
        return new JAXBElement<ParticipantIdentifierType>(_ParticipantIdentifier_QNAME, ParticipantIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceMetadataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", name = "ServiceMetadata")
    public JAXBElement<ServiceMetadataType> createServiceMetadata(ServiceMetadataType value) {
        return new JAXBElement<ServiceMetadataType>(_ServiceMetadata_QNAME, ServiceMetadataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignedServiceMetadataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", name = "SignedServiceMetadata")
    public JAXBElement<SignedServiceMetadataType> createSignedServiceMetadata(SignedServiceMetadataType value) {
        return new JAXBElement<SignedServiceMetadataType>(_SignedServiceMetadata_QNAME, SignedServiceMetadataType.class, null, value);
    }

}
