//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.14 at 01:10:00 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://docs.oasis-open.org/bdxr/ns/SMP/2016/05", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.oasis_open.docs.bdxr.ns.smp._2016._05;
