//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.14 at 01:10:00 AM EET 
//


package org.oasis_open.docs.bdxr.ns.smp._2016._05;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/bdxr/ns/SMP/2016/05}ProcessIdentifier"/>
 *         &lt;element name="ServiceEndpointList" type="{http://docs.oasis-open.org/bdxr/ns/SMP/2016/05}ServiceEndpointList"/>
 *         &lt;element name="Extension" type="{http://docs.oasis-open.org/bdxr/ns/SMP/2016/05}ExtensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessType", propOrder = {
    "processIdentifier",
    "serviceEndpointList",
    "extension"
})
public class ProcessType {

    @XmlElement(name = "ProcessIdentifier", required = true)
    protected ProcessIdentifierType processIdentifier;
    @XmlElement(name = "ServiceEndpointList", required = true)
    protected ServiceEndpointList serviceEndpointList;
    @XmlElement(name = "Extension")
    protected List<ExtensionType> extension;

    /**
     * Gets the value of the processIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessIdentifierType }
     *     
     */
    public ProcessIdentifierType getProcessIdentifier() {
        return processIdentifier;
    }

    /**
     * Sets the value of the processIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessIdentifierType }
     *     
     */
    public void setProcessIdentifier(ProcessIdentifierType value) {
        this.processIdentifier = value;
    }

    /**
     * Gets the value of the serviceEndpointList property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceEndpointList }
     *     
     */
    public ServiceEndpointList getServiceEndpointList() {
        return serviceEndpointList;
    }

    /**
     * Sets the value of the serviceEndpointList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceEndpointList }
     *     
     */
    public void setServiceEndpointList(ServiceEndpointList value) {
        this.serviceEndpointList = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionType }
     * 
     * 
     */
    public List<ExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<ExtensionType>();
        }
        return this.extension;
    }

}
